# Valid TOML config file for Besu 25.7.0
data-path="/node/data"
logging="INFO"

# Network
network-id=3888
bootnodes=["enode://d07678140bcfb5c9f9986f2b36dedb1c3e0ed1a270220caebada14966cbd1f33116bde87416dc76d7eeba38a4f28a83561fc4aa0c67766223076221547de29d3@134.195.198.233:30303 enode://1059a2b16f531b475a06e8370eb16ac2e50e9e663dd2d05dd40d6136875bee5040dc154d6df47b892513265a1143cb80ff0aea50c693400cc516f1552b0b26b4@158.51.120.41:30303"]
node-private-key-file="/node/data"

# Chain
genesis-file="/node/genesis.json"

# RPC Configuration
rpc-http-api=["ETH","NET","QBFT","WEB3","ADMIN"]
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-cors-origins=["*"]
rpc-gas-cap=50000000
host-allowlist=["*"]
revert-reason-enabled=true
data-storage-format="FOREST"
estimate-gas-tolerance-ratio=0.0 
version-compatibility-protection=false 

# WebSocket
rpc-ws-enabled=true

# Performance & Storage
sync-mode="FULL"

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port="9545"
